version: '3.7'

services:
  mysql8:
    image: irvingmeza95/mysql:8
    ports:
      - "3307:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - econsulta
    environment:
      MYSQL_ROOT_PASSWORD: sasa
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  config-server:
    image: irvingmeza95/econsulta-config-server:v1
    mem_limit: 382m 
    mem_reservation: 256m 
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
  eureka-server:
    image: irvingmeza95/eureka-server:v1
    mem_limit: 382m 
    mem_reservation: 256m 
    ports:
      - "8761:8761"
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
  gatewayServer:
    image: irvingmeza95/econsulta-gateway-server:v1
    mem_limit: 382m 
    mem_reservation: 256m 
    ports:
      - "8080:8080"
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
  servicioOauth:
    image: irvingmeza95/econsulta-servicio-oauth:v1
    mem_limit: 319m 
    mem_reservation: 256m 
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
  servicioUsuarios:
    image: irvingmeza95/econsulta-servicio-usuarios:v1
    mem_limit: 512m 
    mem_reservation: 256m 
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - mysql8
      - gatewayServer 
      - servicioVerificacion
  servicioVerificacion:
    image: irvingmeza95/econsulta-servicio-verificacion:v1
    mem_limit: 382m 
    mem_reservation: 256m 
    environment:
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - mysql8
  servicioConsultas:
    image: irvingmeza95/econsulta-servicio-consultas:v1
    mem_limit: 512m 
    mem_reservation: 256m 
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
      - mysql8
  fileManagerService:
    image: irvingmeza95/econsulta-file-manager-service:v1
    mem_limit: 382m 
    mem_reservation: 256m 
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
      - servicioConsultas
      - mysql8
  
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #     - "8088:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   restart: always

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #   restart: always

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #   - grafana-data:/var/lib/grafana
  #   restart: always

networks:
     econsulta:
# volumes:
#   grafana-data: