version: '3.7'

services:
  mysql8:
    image: irvingmeza95/mysql:8
    ports:
      - "3307:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - econsulta
    environment:
      MYSQL_ROOT_PASSWORD: sasa
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  config-server:
    image: irvingmeza95/econsulta-config-server:v1
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
  eureka-server:
    image: irvingmeza95/eureka-server:v1
    ports:
      - "8761:8761"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
  gatewayServer:
    image: irvingmeza95/econsulta-gateway-server:v1
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
  servicioOauth:
    image: irvingmeza95/econsulta-servicio-oauth:v1
    # ports:
    #   - "9100:9100"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
  servicioUsuarios:
    image: irvingmeza95/econsulta-servicio-usuarios:v1
    # ports:
    #   - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - mysql8
      - gatewayServer 
  servicioVerificacion:
    image: irvingmeza95/econsulta-servicio-verificacion:v1
    # ports:
    #   - "8003:8003"
    environment:
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
      - mysql8

networks:
     econsulta: