version: '3.7'

services:
  mysql8:
    image: irvingmeza95/mysql:8
    ports:
      - "3307:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - econsulta
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
  # redis:
  #   image: redis:7.0
  #   container_name: redis
  #   mem_limit: 256m 
  #   mem_reservation: 128m 
  #   command: redis-server --bind 0.0.0.0 --protected-mode no
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - econsulta
  config-server:
    image: irvingmeza95/econsulta-config-server:v1
    container_name: config-server
    mem_limit: 382m 
    mem_reservation: 256m 
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - econsulta
  eureka-server:
    image: irvingmeza95/eureka-server:v1
    container_name: eureka-server
    mem_limit: 382m 
    mem_reservation: 256m 
    ports:
      - "8761:8761"
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
  gatewayServer:
    image: irvingmeza95/econsulta-gateway-server:v1
    container_name: gatewayServer
    mem_limit: 382m 
    mem_reservation: 256m 
    ports:
      - "8080:8080"
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
  servicioOauth:
    image: irvingmeza95/econsulta-servicio-oauth:v1
    container_name: servicioOauth
    mem_limit: 319m 
    mem_reservation: 256m 
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
  servicioUsuarios:
    image: irvingmeza95/econsulta-servicio-usuarios:v1
    container_name: servicioUsuarios
    mem_limit: 512m 
    mem_reservation: 256m 
    restart: always
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - mysql8
      - gatewayServer 
      - servicioVerificacion
  servicioVerificacion:
    image: irvingmeza95/econsulta-servicio-verificacion:v1
    mem_limit: 382m 
    container_name: servicioVerificacion
    mem_reservation: 256m 

    environment:
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
      - CORREO_GMAIL=${CORREO_GMAIL}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - mysql8
  servicioConsultas:
    image: irvingmeza95/econsulta-servicio-consultas:v1
    container_name: servicioConsultas
    mem_limit: 512m 
    mem_reservation: 256m 
    restart: always
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
      - mysql8
  fileManagerService:
    image: irvingmeza95/econsulta-file-manager-service:v1
    container_name: fileManagerService
    mem_limit: 382m 
    mem_reservation: 256m 
    restart: always
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - econsulta
    depends_on:
      - config-server
      - eureka-server
      - servicioUsuarios
      - servicioConsultas
      - mysql8

networks:
     econsulta:
volumes:
  mysql_data:
#   redis_data: